[core]
global_script_dirs = ["~/.local/share/pyst/scripts"]
project_script_dir = ".pyst"
precedence = "local"
offline = false
cwd = "project"
introspection = "safe"

[core.uv]
flags = ["--python-preference=managed"]

[document]
# OpenRouter + Gemini 2.5 Flash (default)
model = "google/gemini-2.5-flash"
api_key_env = "OPENROUTER_API_KEY"
api_base = "https://openrouter.ai/api/v1"
max_tokens = 150
temperature = 0.7
redact = ["SECRET_*", "API_KEY_*", "PASSWORD_*"]

# Alternative configurations you can use:
# 
# For OpenAI GPT-4:
# model = "gpt-4"
# api_key_env = "OPENAI_API_KEY"
# api_base = "https://api.openai.com/v1"
#
# For Anthropic Claude:
# model = "claude-3-haiku-20240307"
# api_key_env = "ANTHROPIC_API_KEY"
# api_base = "https://api.anthropic.com"

[contexts]
  [contexts.default]
  enabled = ["*", "!db-*", "!deploy-prod"]